"""Tests for `sft_config.verify_masking`'s two phases.

The clean-path tests use a committed ~450-token byte-level BPE fixture
(`tests/fixtures/tiny_tokenizer/`, regenerated by the script beside it)
rather than downloading `gpt2`: this check's entire value is being a cheap
tripwire that runs on every PR, and a tripwire that needs the network is
one that gets disabled the first time the Hub rate-limits CI.

The phase-2-only cases drive `_token_level_check` directly with a stub
tokenizer. That is deliberate. Any mask leak large enough for phase 1 to
see is caught by phase 1 first, so the ONLY way to exercise the case phase
2 exists for -- a token that starts inside a non-trainable message and
extends into a generation span -- is to construct the offsets by hand.
"""

from __future__ import annotations

import copy
from pathlib import Path
from typing import Any

import pytest

from fde_training import sft_config

TINY_TOKENIZER = Path(__file__).parent / "fixtures" / "tiny_tokenizer"


class _StubTokenizer:
    """Minimal stand-in exposing exactly what `_token_level_check` reads."""

    def __init__(self, offsets: list[tuple[int, int]], *, is_fast: bool = True) -> None:
        self.is_fast = is_fast
        self._offsets = offsets

    def __call__(self, text: str, **kwargs: Any) -> dict[str, Any]:
        del text, kwargs
        return {"offset_mapping": self._offsets}


@pytest.fixture
def tiny_tokenizer() -> Any:
    transformers = pytest.importorskip("transformers")
    return transformers.AutoTokenizer.from_pretrained(str(TINY_TOKENIZER))


def test_demo_dataset_passes_both_phases(tiny_tokenizer: Any) -> None:
    summary = sft_config.verify_masking(sft_config.demo_dataset(), tiny_tokenizer)
    assert summary["examples_checked"] == 1
    assert summary["mismatches"] == 0
    assert summary["token_mismatches"] == 0
    assert summary["tokens_checked"] > 0


def test_flipped_mask_on_a_tool_message_fails_phase_one(tiny_tokenizer: Any) -> None:
    """Marking a retrieved tool result trainable is the failure this whole
    file exists to catch."""
    dataset = copy.deepcopy(sft_config.demo_dataset())
    dataset[0]["assistant_mask"][3] = True  # the 'tool' message
    with pytest.raises(sft_config.MaskVerificationError) as excinfo:
        sft_config.verify_masking(dataset, tiny_tokenizer)
    assert "DO NOT TRAIN" in str(excinfo.value)
    assert "'role': 'tool'" in str(excinfo.value)


def test_mask_length_mismatch_is_rejected(tiny_tokenizer: Any) -> None:
    dataset = copy.deepcopy(sft_config.demo_dataset())
    dataset[0]["assistant_mask"] = [True, False]
    with pytest.raises(sft_config.MaskVerificationError, match="assistant_mask length"):
        sft_config.verify_masking(dataset, tiny_tokenizer)


def test_slow_tokenizer_is_refused_rather_than_silently_skipped() -> None:
    """A slow tokenizer has no offsets, so a clean report from one would be a
    claim the function never checked."""
    with pytest.raises(sft_config.MaskVerificationError, match="requires a fast tokenizer"):
        sft_config._token_level_check(
            "abc", [(0, 3)], [(0, 3)], [True], _StubTokenizer([(0, 3)], is_fast=False)
        )


def test_token_starting_in_a_non_trainable_message_and_reaching_a_span_fails() -> None:
    """The character-invisible case: message boundary at 12, generation span
    starting exactly there, and one token spanning 10-14. Phase 1 sees no
    overlap with the non-trainable message; the token would still get loss."""
    report = sft_config._token_level_check(
        full_text="tool result>>assistant text",
        gen_spans=[(12, 27)],
        message_char_ranges=[(0, 12), (12, 27)],
        expected_trainable=[False, True],
        tokenizer=_StubTokenizer([(0, 10), (10, 14), (14, 27)]),
    )
    assert report["token_mismatches"] == 1
    detail = report["token_mismatch_details"][0]
    assert detail["message_index"] == 0
    assert detail["char_span"] == [10, 14]
    assert detail["in_generation_span"] is True


def test_boundary_straddling_tokens_are_counted_but_not_fatal() -> None:
    """A token straddling a span boundary inside a TRAINABLE message is
    normal (the template's own markers tokenize that way); it is reported so
    a reviewer can see it, not raised on."""
    report = sft_config._token_level_check(
        full_text="prefix>>assistant text",
        gen_spans=[(8, 22)],
        message_char_ranges=[(0, 22)],
        expected_trainable=[True],
        tokenizer=_StubTokenizer([(0, 6), (6, 10), (10, 22)]),
    )
    assert report["token_mismatches"] == 0
    assert report["boundary_straddling_tokens"] == 1


def test_zero_length_offsets_are_skipped() -> None:
    """Special/added tokens map to an empty span and have no character range
    to attribute to a message."""
    report = sft_config._token_level_check(
        full_text="abcdef",
        gen_spans=[(0, 6)],
        message_char_ranges=[(0, 6)],
        expected_trainable=[True],
        tokenizer=_StubTokenizer([(0, 0), (0, 3), (3, 6), (6, 6)]),
    )
    assert report["tokens_checked"] == 2


def test_tokens_outside_every_generation_span_are_ignored() -> None:
    """Role headers and EOS scaffolding inside a trainable message are not
    marked generation and must not be reported."""
    report = sft_config._token_level_check(
        full_text="<|im_start|>assistant\nhello",
        gen_spans=[(22, 27)],
        message_char_ranges=[(0, 27)],
        expected_trainable=[True],
        tokenizer=_StubTokenizer([(0, 12), (12, 22), (22, 27)]),
    )
    assert report["token_mismatches"] == 0
    assert report["tokens_checked"] == 3
