"""Stage and upload an agent's CodeZip payload for AgentCore's `code`
artifact mode.

What `runtimes.py --artifact-mode code` requires
------------------------------------------------
`CreateAgentRuntime`'s code configuration points at an S3 `{bucket, prefix}`
and declares `runtime='PYTHON_3_12'` with `entryPoint=['agent.py']`. That
entry point is a bare filename, not a package path, so AgentCore expects the
prefix to contain **one agent's** contents flattened to its root: an
`agent.py` at the top, the importable packages beside it, and every
third-party dependency vendored in. Until now nothing in this repo produced
that layout, so the code path in `runtimes.py` was unreachable in practice
and README's deploy recipe named a `codezip` step that did not exist.

The layout this module builds, per agent::

    <staging>/
      agent.py            <- the shim; `from fde_agents.<agent>.agent import app`
      fde_agents/         <- workspace source, copied
      fde_mcp/            <- workspace source, copied (tracing + logging + config)
      <third-party deps>  <- vendored wheels, arm64 / cp312

Why the dependency install is so specific
------------------------------------------
`pip install --target ... --platform manylinux2014_aarch64 --only-binary=:all:`
is three constraints doing three jobs. `--platform`/`--python-version` make
the vendored set match the runtime rather than this laptop -- the same ARM64
trap `docs/11-python-conventions.md` §8 calls out for the container path,
where an x86 build pushes and runs fine locally and then fails in the
runtime. `--only-binary=:all:` turns "this dependency only ships an sdist"
into a loud failure at packaging time instead of a silent host-architecture
build that gets uploaded and breaks on first invocation.

`--stage-only` builds the layout and stops. That is the path CI and the unit
tests exercise; S3 upload needs credentials and is manual/CI-only.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

from fde_mcp.logging import get_logger

log = get_logger(__name__)

AGENT_NAMES = ("engagement", "workflow", "development")

# Kept in lockstep with `runtimes.py`'s `codeConfiguration.runtime`. The repo
# pins the same interpreter in the root `.python-version`.
PYTHON_VERSION = "3.12"
MANYLINUX_PLATFORM = "manylinux2014_aarch64"

# The workspace packages copied into every agent's payload. `fde_training` is
# deliberately absent: an agent runtime that could import it could import
# torch, which is the exact separation the three-package split exists to
# enforce (docs/11-python-conventions.md §2).
VENDORED_WORKSPACE_PACKAGES = ("fde_agents", "fde_mcp")


def _find_repo_root(start: Path | None = None) -> Path:
    """Walk up to the workspace root (the directory holding `packages/` and
    the root `pyproject.toml`).

    Searched rather than counted in `parents[n]` because this module reads
    workspace SOURCE trees: an index that is off by one produces a
    `FileNotFoundError` pointing at a plausible-looking wrong path, and
    packaging is exactly where a wrong-but-plausible path is expensive.
    Packaging runs from a checkout by definition, so this always resolves
    in the environments that call it.
    """
    for candidate in (start or Path(__file__).resolve()).parents:
        if (candidate / "packages").is_dir() and (candidate / "pyproject.toml").is_file():
            return candidate
    msg = "could not locate the workspace root (no ancestor with packages/ and pyproject.toml)"
    raise FileNotFoundError(msg)


def build_entrypoint_shim(agent_name: str) -> str:
    """The text of the `agent.py` AgentCore invokes.

    Each agent module already builds its `BedrockAgentCoreApp` at import
    time (`app, handler = create_app(_CONFIG)`), so the shim is a re-export
    plus `app.run()` -- deliberately not a copy of the agent module, which
    would be a second definition of the entrypoint to keep in sync.

    Args:
        agent_name: One of `AGENT_NAMES`.

    Returns:
        Python source for the staged `agent.py`.

    Raises:
        ValueError: if `agent_name` is not a known agent.
    """
    if agent_name not in AGENT_NAMES:
        msg = f"unknown agent {agent_name!r}; must be one of {list(AGENT_NAMES)}"
        raise ValueError(msg)
    return (
        f'"""AgentCore CodeZip entry point for the {agent_name} agent.\n\n'
        f"Generated by fde_agents.deploy.codezip -- do not edit in place; the\n"
        f"agent itself lives in fde_agents/{agent_name}/agent.py.\n"
        f'"""\n\n'
        f"from __future__ import annotations\n\n"
        f"from fde_agents.{agent_name}.agent import app\n\n"
        f'if __name__ == "__main__":\n'
        f"    app.run()\n"
    )


def _copy_workspace_sources(staging_dir: Path, repo_root: Path) -> list[str]:
    copied = []
    for package in VENDORED_WORKSPACE_PACKAGES:
        member = "fde-agents" if package == "fde_agents" else package.replace("_", "-")
        src = repo_root / "packages" / member / "src" / package
        if not src.is_dir():
            msg = f"workspace package source not found: {src}"
            raise FileNotFoundError(msg)
        shutil.copytree(
            src,
            staging_dir / package,
            dirs_exist_ok=True,
            ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
        )
        copied.append(package)
    return copied


def _install_dependencies(staging_dir: Path, repo_root: Path) -> None:
    """Export the locked dependency set and vendor it into `staging_dir`.

    Runs `uv export` (so the versions are the lockfile's, not a fresh
    resolution) and then a cross-platform `pip install --target`.
    """
    requirements = staging_dir.parent / f"{staging_dir.name}-requirements.txt"
    export = subprocess.run(
        [
            "uv",
            "export",
            "--package",
            "fde-agents",
            "--no-dev",
            "--no-emit-workspace",
            "--frozen",
            "-o",
            str(requirements),
        ],
        cwd=repo_root,
        capture_output=True,
        text=True,
        check=False,
    )
    if export.returncode != 0:
        msg = f"uv export failed: {export.stderr.strip()}"
        raise RuntimeError(msg)

    install = subprocess.run(
        [
            sys.executable,
            "-m",
            "pip",
            "install",
            "--target",
            str(staging_dir),
            "--python-version",
            PYTHON_VERSION,
            "--platform",
            MANYLINUX_PLATFORM,
            "--only-binary=:all:",
            "--no-compile",
            "-r",
            str(requirements),
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if install.returncode != 0:
        msg = (
            f"vendoring dependencies failed (see --only-binary in this module's "
            f"docstring for why an sdist-only dependency fails here rather than "
            f"silently vendoring a host build):\n{install.stdout[-2000:]}\n{install.stderr[-2000:]}"
        )
        raise RuntimeError(msg)


def stage_agent(
    agent_name: str,
    staging_dir: Path,
    *,
    repo_root: Path | None = None,
    install_deps: bool = True,
) -> Path:
    """Build one agent's flattened CodeZip payload under `staging_dir`.

    Args:
        agent_name: One of `AGENT_NAMES`.
        staging_dir: Destination directory; created if absent, and cleared
            first so a re-stage never inherits a previous run's files.
        repo_root: Workspace root; defaults to this file's own repo.
        install_deps: Vendor third-party dependencies. Tests and fast dev
            loops set this False to assert the layout without a network
            round trip.

    Returns:
        `staging_dir`, for chaining into `upload`.
    """
    root = repo_root or _find_repo_root()
    if staging_dir.exists():
        shutil.rmtree(staging_dir)
    staging_dir.mkdir(parents=True)

    (staging_dir / "agent.py").write_text(build_entrypoint_shim(agent_name))
    copied = _copy_workspace_sources(staging_dir, root)
    if install_deps:
        _install_dependencies(staging_dir, root)

    log.info(
        "codezip_staged",
        agent_name=agent_name,
        staging_dir=str(staging_dir),
        workspace_packages=copied,
        vendored_deps=install_deps,
    )
    return staging_dir


def s3_key(prefix_root: str, agent_name: str, relative_path: str) -> str:
    """The S3 key one staged file lands at.

    Mirrors `runtimes.py:_build_artifact`'s prefix computation exactly
    (`<prefix_root>/<agent>`), which is what makes the uploaded layout the
    one AgentCore then reads.
    """
    return f"{prefix_root.rstrip('/')}/{agent_name}/{relative_path}"


def upload(staging_dir: Path, bucket: str, agent_name: str, prefix_root: str) -> int:
    """Upload every staged file to S3. Lazily imports boto3, mirroring the
    rest of `deploy/`.

    Args:
        staging_dir: Output of `stage_agent`.
        bucket: Target S3 bucket.
        agent_name: One of `AGENT_NAMES`; part of the key prefix.
        prefix_root: Key prefix root, matching `runtimes.py`'s
            `--code-prefix-root`.

    Returns:
        Number of objects uploaded.
    """
    import boto3  # noqa: PLC0415

    client = boto3.client("s3")
    n = 0
    for path in sorted(staging_dir.rglob("*")):
        if not path.is_file():
            continue
        key = s3_key(prefix_root, agent_name, path.relative_to(staging_dir).as_posix())
        client.upload_file(str(path), bucket, key)
        n += 1
    log.info("codezip_uploaded", agent_name=agent_name, bucket=bucket, objects=n)
    return n


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(prog="fde-agents-deploy codezip", description=__doc__)
    p.add_argument("--agents", nargs="+", default=list(AGENT_NAMES), choices=AGENT_NAMES)
    p.add_argument("--code-bucket", help="S3 bucket to upload to (required unless --stage-only).")
    p.add_argument(
        "--code-prefix-root",
        default="fde-agents",
        help="Key prefix root; must match `runtimes --code-prefix-root`.",
    )
    p.add_argument(
        "--stage-only",
        metavar="DIR",
        help="Build the payload under DIR/<agent> and skip the upload entirely.",
    )
    p.add_argument(
        "--no-deps",
        action="store_true",
        help="Skip vendoring third-party dependencies (layout check only).",
    )
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    if not args.stage_only and not args.code_bucket:
        print("--code-bucket is required unless --stage-only DIR is given", file=sys.stderr)
        return 2

    import tempfile  # noqa: PLC0415 -- only the upload path needs a scratch dir

    base = (
        Path(args.stage_only) if args.stage_only else Path(tempfile.mkdtemp(prefix="fde-codezip-"))
    )
    for agent_name in args.agents:
        staging = base / agent_name
        stage_agent(agent_name, staging, install_deps=not args.no_deps)
        if args.stage_only:
            print(f"{agent_name}: staged at {staging}")
            continue
        n = upload(staging, args.code_bucket, agent_name, args.code_prefix_root)
        print(
            f"{agent_name}: {n} objects -> s3://{args.code_bucket}/"
            f"{args.code_prefix_root.rstrip('/')}/{agent_name}/"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
